FROM node:20-slim AS build
WORKDIR /src

COPY package.json .
RUN npm install

COPY tsconfig.json .
COPY src ./src
RUN npm run build

FROM node:20-slim
WORKDIR /app

COPY package.json .
RUN npm install --omit=dev

COPY --from=build /src/dist ./dist

EXPOSE 8003
CMD ["node", "dist/main.js"]
